workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - google_credentials # <-- (Includes GCLOUD_KEY_FILE, GOOGLE_CREDENTIALS)
      vars:
        FIREBASE_PROJECT: "fe-community-dev"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK with Flutter
        script: |
          flutter build apk --debug
      # - name: Create debug and test APK
      #   script: |
      #     set -ex
      #     cd android
      #     ./gradlew app:assembleAndroidTest
      #     ./gradlew app:assembleDebug -Ptarget="$CM_BUILD_DIR/integration_test/app_test.dart"
      # - name: Run Firebase Test Lab tests
      #   script: |
      #     set -ex

      #     echo $GCLOUD_KEY_FILE | base64 --decode > ./gcloud_key_file.json

      #     gcloud auth activate-service-account --key-file=gcloud_key_file.json

      #     gcloud --quiet config set project $FIREBASE_PROJECT

      #     gcloud firebase test android run \
      #       --type instrumentation \
      #       --app build/app/outputs/apk/debug/app-debug.apk \
      #       --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
      #       --timeout 3m
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    triggering:
      events: 
        - push
      # branch_patterns:             
      # - pattern: 'master'
      #   include: true
      #   source: true
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - google_credentials
      vars:
        FIREBASE_PROJECT: "fe-community-dev"
        BUNDLE_ID: "dev.flutterexplained.cicdtutorial"
        TEST_BUNDLE_ID: "dev.flutterexplained.cicdtutorial.uitests.xctrunner"
    scripts:
      - name: Build app for testing
        script: 
          flutter build ios --debug  